CREATE TABLE smoothies20 (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    flavor TEXT NOT NULL,
    size INTEGER NOT NULL DEFAULT 20,
    calories INTEGER NOT NULL,
    total_fat FLOAT,
    saturated_fat FLOAT,
    trans_fat FLOAT,
    cholesterol FLOAT,
    total_carbohydrates FLOAT,
    dietary_fiber FLOAT,
    sugars FLOAT,
    protein FLOAT
);